### ISSUE TITLE
Language selector

### ISSUE THREAD

**Issue by mbuhnici** [Birssan/grav-theme-nucleare#15]
I'm having issues with the drop down language selector. It doesn't load any text in drop down menu and one of the languages path is set to /1/ instead of the language code.

![image](https://cloud.githubusercontent.com/assets/6874110/15958323/8ec4ac14-2efd-11e6-9ee9-2ca3e762a660.png)
 and 
![image](https://cloud.githubusercontent.com/assets/6874110/15958338/aeac0446-2efd-11e6-9a26-7be39b3ee8ed.png)

Or am I doing something wrong?

**Comment by seb-vial** [comment]
I have this issue as well.
I haven't changed anything in months, I have to check if there's been a change in Grav code about the way languages are managed.

**Comment by seb-vial** [comment]
There was a small change in the langswitcher plugin. I fixed the template.
